spring:
  datasource:
    url: ${datasourceUrl:jdbc:postgresql://localhost:5432/drone_communication}
    username: ${datasourceUsername:postgres}
    password: ${datasourcePassword:password}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/master-changelog.xml
